services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d expense_tracker"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://dev_user:dev_password@postgres:5432/expense_tracker
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SECRET_KEY: ${SECRET_KEY:-dev-secret-key-change-in-production}
      ENVIRONMENT: development
      VAPID_PUBLIC_KEY: "BFeUF2h6jSBjpXsJcKsDHChxU4PEgTHFORo6mlREJLOG5ulg-0V-s9WLi1xYshlkzmBIkXZ9MuDZ2Cl22QQdh4I"
      VAPID_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2R1QnN0aDJ1U3dOY1lYUXEKQXBWSktVRlVhdWZyRTR6Z09IOVBJSG93eFBPaFJBTkNBQVJYbEJkb2VvMGdZNlY3Q1hDckF4d29jVk9EeElFeAp4VGthT3BwVVJDU3podWJwWVB0RmZyUFZpNHRjV0xJWlpNNWdTSkYyZlRMZzJkZ3BkdGtFSFllQwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg"
      VAPID_CLAIM_EMAIL: "admin@expense-tracker.com"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  uploads: